# Generated by Django 4.1.2 on 2023-04-18 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_profile_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='ambassador',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
