# Generated by Django 4.1.2 on 2023-04-26 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_notification_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='url',
            field=models.TextField(default='', null=True),
        ),
    ]
