# Generated by Django 4.1.2 on 2023-04-26 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_notification_created_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='new_notification_count',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
