# Generated by Django 4.1.2 on 2023-04-29 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0026_rename_eventhearts_eventheart'),
        ('users', '0010_profile_new_notification_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='dont_recommend_events',
            field=models.ManyToManyField(blank=True, default=None, null=True, related_name='events_dont_recommend', to='events.event'),
        ),
    ]
