# Generated by Django 4.1.2 on 2023-04-05 13:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('time', models.DateField()),
                ('location', models.CharField(max_length=100)),
                ('users', models.ManyToManyField(related_name='events_attending', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
