# Generated by Django 4.1.2 on 2023-04-11 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0010_remove_event_is_past'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='old_post',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
