# Generated by Django 4.1.2 on 2023-04-11 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0011_event_old_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='old_post',
        ),
        migrations.AddField(
            model_name='event',
            name='maximum_people',
            field=models.IntegerField(blank=True, default=3),
        ),
    ]
