# Generated by Django 4.1.2 on 2023-04-16 15:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('social_clubs', '0001_initial'),
        ('events', '0012_remove_event_old_post_event_maximum_people'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='social_club',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='social_clubs.socialclub'),
        ),
    ]
