# Generated by Django 4.1.2 on 2023-04-26 00:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0016_eventcomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='create_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 26, 3, 16, 47, 293999)),
        ),
    ]
