# Generated by Django 4.1.2 on 2023-04-26 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0019_alter_event_create_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='create_time',
        ),
        migrations.AddField(
            model_name='event',
            name='created_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
