# Generated by Django 4.1.2 on 2023-04-26 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0020_remove_event_create_time_event_created_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventcomment',
            name='created_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
