# Generated by Django 4.1.2 on 2023-04-29 01:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0023_remove_event_dislikes_remove_event_likes_eventhearts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventhearts',
            name='likes',
        ),
        migrations.AddField(
            model_name='eventhearts',
            name='liked',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='eventhearts',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes_event', to='events.event'),
        ),
        migrations.AlterField(
            model_name='eventhearts',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users_likes', to=settings.AUTH_USER_MODEL),
        ),
    ]
