# Generated by Django 4.1.2 on 2023-04-29 01:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0024_remove_eventhearts_likes_eventhearts_liked_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventhearts',
            name='liked',
        ),
    ]
