# Generated by Django 4.1.2 on 2023-04-29 01:38

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0025_remove_eventhearts_liked'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EventHearts',
            new_name='EventHeart',
        ),
    ]
