# Generated by Django 4.1.2 on 2023-05-01 02:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0026_rename_eventhearts_eventheart'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventcomment',
            name='reply_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reply_comments', to='events.eventcomment'),
        ),
    ]
