# Generated by Django 4.1.2 on 2023-04-16 15:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('social_clubs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialclub',
            name='managers',
            field=models.ManyToManyField(related_name='admin_of', to=settings.AUTH_USER_MODEL),
        ),
    ]
