# Generated by Django 4.1.2 on 2023-04-20 12:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('social_clubs', '0002_socialclub_managers'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialClubImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='social_club_images/')),
                ('social_club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_club_images', to='social_clubs.socialclub')),
            ],
        ),
    ]
